Analyze Data:
  alias: analyze_data
  menu_list:
  - id: 0
    label: Select Graph
Main Menu:
  alias: main_menu # DONE
  menu_list:
  - id: 0
    label: Create New Account # DONE, to be completed
  - id: 1
    label: Load Account # DONE
  - id: 2
    label: Save Account # DONE
  - id: 3
    label: Delete Account # DONE
  - id: 4
    label: Show Accounts # DONE
  - id: 5
    label: Analyze Data # TBD
  - id: 6
    label: Manage Account # TBD
  - id: 7
    label: Settings # TBD
Manage Account:
  alias: manage_account
  menu_list:
  - id: 0
    label: Add Year Balance
  - id: 1
    label: Remove Year Balance
  - id: 2
    label: Manage Year Balance
Manage Expenditure:
  alias: manage_expenditure
  menu_list:
  - id: 0
    label: Modify Expenditure Type
  - id: 1
    label: Modify Expenditure Value
  - id: 2
    label: Modify Expenditure Description
Manage Income:
  alias: manage_income
  menu_list:
  - id: 0
    label: Modify Income Type
  - id: 1
    label: Modify Income Value
  - id: 2
    label: Modify Income Description
Manage Month Balance:
  alias: manage_month_balance
  menu_list:
  - id: 0
    label: Add Income
  - id: 1
    label: Remove Income
  - id: 2
    label: Manage Income
  - id: 3
    label: Add Expenditure
  - id: 4
    label: Remove Expenditure
  - id: 5
    label: Manage Expenditure
Manage Year Balance:
  alias: manage_year_balance
  menu_list:
  - id: 0
    label: Add Month Balance
  - id: 1
    label: Remove Month Balance
  - id: 2
    label: Manage Month Balance
Settings:
  alias: manage_settings
  menu_list:
  - id: 0
    label: Select Language # DONE
  - id: 1
    label: Select Menu Background Color # DONE
  - id: 2
    label: Select Menu Foreground Color # DONE
